questions:
  - question: "Observe the following code:
    \n\n `def add_nums(*args):`
    \n\n\t total = 0
    \n\n\t for num in args:
    \n\n\t\t total += num
    \n\n\t return total
    \n\n `try`:
    \n\n\t total = add_nums(1, 2, 3, 4, 5)
    \n\n\t print(total)
    \n\n `except`:
    \n\n\t print('An error occurred')
    \nWhat is the output?"

  - question: "Observe the following code:
    \n\n `def add_nums(*args):`
    \n\n\t total = 0
    \n\n\t for num in args:
    \n\n\t\t total += num
    \n\n\t return total
    \n\n `try`:
    \n\n\t total = add_nums([1, 2, 3, 4, 5])
    \n\n\t print(total)
    \n\n `except`:
    \n\n\t print('An error occurred')
    
    \nWhat is the output?"
  
  - question: "Observe the following code:
    \n\n `def add_nums(*args):`
    \n\n\t total = 0
    \n\n\t for num in args:
    \n\n\t\t total += num
    \n\n\t return total
    \n\n `try`:
    \n\n\t total = add_nums([1, 2, 3, 4, 5])
    \n\n\t print(total)
    \n\n `except`:
    \n\n\t print('An error occurred')
    \n\n `else:`
    \n\n\t print('No error occurred')
    \n\n `finally:`
    \n\n\t print('Exiting the error handling clauses')

    \nWhat is the output?"

  - question: "Observe the following code:
    \n\n `def add_nums(*args):`
    \n\n\t total = 0
    \n\n\t for num in args:
    \n\n\t\t total += num
    \n\n\t return total
    \n\n `try`:
    \n\n\t total = add_nums(1, 2, 3, 4, 5)
    \n\n\t print(total)
    \n\n `except`:
    \n\n\t print('An error occurred')
    \n\n `else:`
    \n\n\t print('No error occurred')
    \n\n `finally:`
    \n\n\t print('Exiting the error handling clauses')
    \nWhat is the output?"
    
  