# Error Handling

## Setup

### What do i need open?
- VSCode open on the home page
    - `.Error Handling.ipynb` notebook
- Web Browser with google open:
    - You will search "print an error in python"
- OBS
    

### What recording scenes do I need open?

- Screencapture of vscode with your webcam capture in the corner
- Webcam capture in full screen
- Safari (or any browser) with Google open

## Script

- __`[START SCENE] webcam in full screen`__
    - Errors happen, and if you have already used Python, you know that errors are more common than what we want
    - In many cases, the error can be avoided if we debug the code
    - However, that is not possible everytime we execute our code
    - If the error we get is expected, we can add a statement that makes an exception for the error instead of breaking
    - and, in that case, Python will NOT stop the execution due to an error

<br>

- __`[SWITCH SCENE] Open VSCode`__
- __`[FIRST CELL] Defining a division function`__
    - In this cell, we define a simple function that divides two numbers
    - And then we call the function with two inputs
    - __`[RUN THE CELL]`__ After running it, everything works completely fine

<br>

- __`[NEXT CELL] Using 0 as the second number`__
    - But if I use 0 as the second number
    - __`[RUN THE CELL]`__ This is raising an error, which reads `ZeroDivisionError`
    - Python will stop the execution at that point, and, if we had more code, the rest of it won't run
    - For these cases, we can use error handling statements
    - before I show that, I'll mention a few things:
        - another way to say that an error has been raised is to say that it has been "thrown"
        - and another way to say that an error is being handled is to say that is you are "catching" the error
        - another word for an error is an exception, so you'll hear me talking about raising exceptions, throwing exceptions, and catching exceptions

<br>

- __`[NEXT CELL] Show the image`__
    - An error handling statement `TRY`es a block of code, and if that block of code raises an error, it will except the error and execute a different block    
    - You can think about it as something similar to an `if-else` statement, but the difference is that we are handling exceptions rather than boolean conditions
    - Catching an error in Python is done using the `try-except` statement. 
    - Optionally, you can add two more statement `else` which runs a code if we don't get any error
    - and `finally` which will run a block of code regardless of whether we obtained an error

<br>

- __`[NEXT CELL] Try except with the function`__
    - Let's focus first on the try except statement, and then we will add more commands
    - We are going to try to execute the function with the second argument equals to 0 to force an error
    - The except command will catch the error and it will run the block of code inside it, which assigns `None` to the result of the division 
    - __`[RUN THE CELL]`__ 
        - You can see that Python tried to execute the code within the `try` body
        - But encountered an error and jumped to the `except` body
        - After finishing the `try-except` statement, it goes out and keep executing the rest
    - Notice that if the `try` block runs normally, the code inside `except` won't run at all
    - __`[CHANGE num_2 for 2 and RE-RUN the cell]`__
        - You can see that the result looks correct
        - and that the print statement in the `except` block wasn't executed 

<br>

- __`[NEXT CELL] Try except with three arguments`__
    - So, we know that the error is caused because of a number causing zero division
    - But we might have different sources of errors
    - For example, the function doesn't accept three arguments
    - So, if we run the cell will it detect the error as a ZeroDivisionError? __`[RUN THE CELL]`__
    - Python didn't throw any error at all, but it says that the second argument is zero
    - The problem here lies in the fact that we have programmed it to detect ANY sort of error
    - Doing this is a really bad practice, if you are going to use error handling, you have to be specific about the error you expect

<br>

- __`[NEXT CELL] Try except with three arguments and ZeroDivisionError`__
    - Now, we are explicitly telling Python what error is going to be expected
    - And after running the cell __`[RUN THE CELL]`__ , we can see that this `except` didn't catch the error
    - In fact, it threw a different error: `TypeError`
    - So, let's add that specific type of error to the list of possible errors

<br>

- __`[NEXT CELL] Try except with three arguments and two except statements`__
    - To do so, we can add another `except` block
    - Let's say that, if we find a code with more than two arguments, we are just dividing the first two arguments
    - __`[RUN THE CELL]`__ So, in this case, we can see that the code jumps from the `try` block to the `except TypeError` block
    - Let's say that we don't know what error we are expecting
    - We can still use an `except` block with no specific error to catch all of those that weren't defined yet

<br>

- __`[NEXT CELL] Try except with two ints and three except`__
    - In this case, we are forcing a NameError because we will use a variable that is not defined in the try block
    - The try-except error will check if the given error is within those that have been defined
    - __`[RUN CELL]`__ And it will see that it's not amongst them, so it will go to the last `except` block
    - However, can we see the type of error it would throw?
    - Let's ask Google!

<br>

- __`[SWITCH SCENE] Open Browser`__
- __`[OPEN GOOGLE] Search "print an error in python"`__
    - Stackoverflow always there to help us!
    - Let's open that link

- __`[OPEN URL] Stackoverflow: "How to print an exception in Python? - Stack Overflow"`__
    - Let's take a look at the first answer...
- __`[SCROLL DOWN to the first answer]`__
    - So for Python 3.x we need to use the as keyword after our error type, 
        - except Exception as e 
        - and `e` so that it will be assigned to the instance of the exception thrown
    - Good! let's put that in practice

<br>


- __`[SWITCH SCENE] Open VSCode`__
- __`[NEXT CELL] Try except with two ints and three except printing the type of error`__
    - We assigned the exception to the variable `e` and printed out inside the block
    - __`[RUN THE CELL]`__ And we can see what the error was, so next time we can iterate through the code and include that type of error to be caught

<br>

- As mentioned we can optionally include more options to the this block, namely `else` and `finally`
- __`[NEXT CELL] Adding an else`__
    - The body in the `else` statement of an error handling code is executed only when the body inside `try` executed with no problem
    - If the code in `try` throws an error, it will go to `except` and then the code in `else` won't run at all
    - `else` is added after the `except`s statement
    - Let's say that, if everything goes right, the result of the division is casted to an integer
    - So after running the cell __`[RUN CELL]`__, we can see that the messages from the `try` and the `else` statements run
    - and that the result is an integer

<br>

- __`[NEXT CELL] Adding an else but num_2 is 0`__
    - However, if the code in `try` fails, it will go to one `except` and then it will skip the `else`
    - In this example __`[RUN CELL]`__, we can see that the `try` code fails, and then it will run the code corresponding to the ZeroDivisionError
    - But the message from `else` doesn't run

<br>

- To finish off, we have the `finally` statement
- __`[NEXT CELL] Adding finally`__
    - `finally` will run regardless the code in `try` fails or not
    - So, in this code, the code in `try` will run normally, then it will go to `else` and lastly, to `finally`
    - __`[RUN CELL]`__ We can see that the last message is the one included in the `finally`

<br>

- __`[NEXT CELL] Adding finally but num_2 = 0`__
    - If the code in `try` fails, the code will go to one of the exceptions and then to `finally`
    - __`[RUN CELL]`__ We can see that the last message is the one included in the `finally` but now `else` has been skipped

## Summary

- __`[SWITCH SCENE] webcam in full screen`__

    - So now you know how to catch errors and act accordingly using the control flow you want
    - This will be very helpful to make your code more robust
    - But be careful, don't add `except` statements just to make your code run always
    - It is important to know what type of exceptions Python is throwing and getting the underlying root cause of the problem
    - Let's review what we have discussed in this video
        - We just saw how to prevent Python from stopping your code when it encounters an error using try except
        - If the code we include in the `try` statement fails, it will go to the code in the `except`
        - We can be specific about the error we are expecting in the except statement
        - and actually, it is a good practice to specify all type of errors we are expecting
        - We can use two additional statements:
            - `else` which will run only if the code in `try` doesn't throw an error
            - and `finally` which will run no matter the code in `try` throws an error or not
        - Thus, a whole flow would `try`, `else`, `finally`, if everything works correctly
        - and `try` `except` and `finally`, if the code in `try` fails